name: kubeflow-fairing
channels:
  - anaconda
  - defaults
dependencies:
  - ipykernel=5.1.3=py37h39e3cac_0
  - ipython=7.9.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - jupyter_core=4.6.1=py37_0
  - jupyterlab=1.2.2
  - jupyterlab_server=1.0.6=py_0
  - nb_conda=2.2.1=py37_0
  - nb_conda_kernels=2.2.2=py37_0
  - nbconvert=5.6.1=py37_0
  - nbformat=4.4.0=py37_0
  - pip=19.3.1=py37_0
  - yaml=0.1.7
  - zeromq=4.3.1
  - pip:
    - ipywidgets==7.5.1
    - jupyter==1.0.0
    - jupyter-client==6.1.3
    - jupyter-console==6.1.0
    - kfp==0.2.5
    - kfp-server-api==0.1.40
    - papermill==2.1.0
    - paramiko==2.7.1
