name: "Test Starter Pack using KinD + kfx"
on: [pull_request, push]

jobs:
  kind:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: KinD Create Cluster
      uses: engineerd/setup-kind@v0.3.0
      with:
        name: "kfx-k8s"
        version: "v0.7.0"
        config: "kind/kind-config.yaml"
    
    - name: KinD Cluster Check
      run: |
        kubectl cluster-info
        kubectl get pods -n kube-system
    
    - name: Setup Kubeflow (using kfx)
      run: |
        chmod +x ${GITHUB_WORKSPACE}/test/kfx-smoketest.sh
        ${GITHUB_WORKSPACE}/test/kfx-smoketest.sh

    - name: Setup Helm
      run: |
        wget https://get.helm.sh/helm-v3.1.2-linux-amd64.tar.gz
        tar -zxvf helm-v3.1.2-linux-amd64.tar.gz
        mv linux-amd64/helm ${GITHUB_WORKSPACE}/helm
    - name: Setup NFS (using Helm)
      run: |
        ${GITHUB_WORKSPACE}/helm repo add stable https://kubernetes-charts.storage.googleapis.com/
        ${GITHUB_WORKSPACE}/helm repo update
        ${GITHUB_WORKSPACE}/helm install stable/nfs-server-provisioner --set=persistence.enabled=true,persistence.storageClass=standard,persistence.size=20Gi --generate-name
        kubectl create -f ${GITHUB_WORKSPACE}/test/nfs-pvc.yaml

    - name: Run BLERSSI pipeline
      run: |
        echo "Launching Pipeline..."
