name: "Test Starter Pack using KinD + kfx"
on: [pull_request, push]

jobs:
  kind:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - uses: engineerd/setup-kind@v0.3.0
      with:
        name: "kfx-k8s"
        version: "v0.7.0"
        config: "kind/kind-config.yaml"
    
    - name: KinD Cluster Check
      run: |
        kubectl cluster-info
        kubectl get pods -n kube-system
    
    - name: Setup Kubeflow (using kfx)
      run: |
        chmod +x ${GITHUB_WORKSPACE}test/kind-smoketest.sh
        ${GITHUB_WORKSPACE}test/kind-smoketest.sh

    - name: Setup NFS
      run: |
        chmod +x ${GITHUB_WORKSPACE}test/starter-pack-smoketest.sh
        ${GITHUB_WORKSPACE}test/starter-pack-smoketest.sh

    - name: Run BLERSSI pipeline
      run: |
        echo "Launching Pipeline..."
